version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: demo_db
    ports:
      - "5432:5432"
    volumes:
          - postgres-db-volume:/var/lib/postgresql/data

volumes:
  postgres-db-volume: